// ============================================================
// MARKETING 8-BALL — DATABASE
// To add quotes: add a string to the relevant category array
// To add marketers: add an object to the MARKETERS array
// ============================================================

export const MARKETERS = [
  {
    name: "Chad Leverage",
    title: "Chief Visionary Officer",
    company: "GrowthStack Partners",
  },
  {
    name: "Brittany Synergize",
    title: "VP of Human-Centric Growth",
    company: "BrandPulse Agency",
  },
  {
    name: "Kyle Mindset",
    title: "Founder & Chief Evangelist",
    company: "The Funnel Collective",
  },
  {
    name: "Tiffany Reach",
    title: "Director of Omnichannel Everything",
    company: "PivotLab",
  },
  {
    name: "Brandon ROI",
    title: "Brand Philosopher & Growth Hacker",
    company: "Hustle & Heart",
  },
  {
    name: "Madison Narrative",
    title: "Head of Story-Driven Performance",
    company: "Authentic Metrics Co.",
  },
  {
    name: "Tyler Disrupt",
    title: "Chief Disruption Architect",
    company: "Disrupt.io",
  },
  {
    name: "Kayla Purpose",
    title: "SVP of Values-Led Revenue",
    company: "ImpactScale Studio",
  },
  {
    name: "Brock Awareness",
    title: "Principal Ecosystem Strategist",
    company: "Synergy Unlimited",
  },
  {
    name: "Amber Funnel",
    title: "Head of Frictionless Journeys",
    company: "ConversionMind Agency",
  },
  {
    name: "Jared Touchpoint",
    title: "Chief Experience Alchemist",
    company: "TouchpointLab",
  },
  {
    name: "Destiny Pivot",
    title: "VP of Agile Storytelling",
    company: "NarrativeOS",
  },
  {
    name: "Cody Bandwidth",
    title: "Director of Scalable Emotions",
    company: "FeelMetrics Inc.",
  },
  {
    name: "Skylar Data",
    title: "Chief Intuition Officer",
    company: "DataDriven Feelings LLC",
  },
  {
    name: "Hunter Engagement",
    title: "Head of Viral Authenticity",
    company: "OrganicReach Global",
  },
];

// ============================================================
// QUOTES — add new strings to any category below
// ============================================================

const QUOTES_BY_CATEGORY = {

  authenticity: [
    "Authenticity is the new black. Brands that fail to disrupt their own narrative will be disrupted by someone else's ecosystem.",
    "The most authentic thing a brand can do is be unapologetically itself — just make sure that self has been A/B tested first.",
    "Consumers crave realness. Which is why we recommend scripting your authenticity at least six weeks in advance.",
    "Authentic storytelling isn't about being real — it's about being real enough that the algorithm rewards you for it.",
    "Vulnerability is your biggest untapped growth lever. Share your brand's struggles. Ideally between 9am and 11am on a Tuesday for maximum engagement.",
    "The brands winning right now are the ones being completely transparent — about everything except their actual business model.",
    "Authenticity at scale is still authenticity. We've automated ours and honestly it's performing better than when humans were doing it.",
    "Your audience can smell inauthenticity from a mile away. That's why our authentic content calendar is planned eighteen months out.",
    "People don't want to be marketed to. They want to be in a relationship with your brand. A highly optimised, retargeted relationship.",
    "True authenticity means saying what your audience wants to hear, in a way that feels completely unscripted.",
    "Raw, unpolished content builds the deepest trust. We spent $400k on production to achieve that raw, unpolished look.",
    "Brands need to take a stand. Just make sure legal has approved the stand, and that it doesn't alienate anyone over 18.",
    "The future belongs to brands that are real, human, and relatable — all of which can be outsourced.",
    "Stop marketing and start connecting. Then measure those connections with a 47-point attribution dashboard.",
    "Authenticity is free. Authentic-looking content starts at $15,000 per campaign.",
  ],

  disruption: [
    "If you're not disrupting yourself, someone else is doing it for you. Preferably someone with worse fonts.",
    "Every industry is one bold pivot away from irrelevance. Stay paranoid. Stay agile. Stay funded.",
    "Disruption isn't a strategy — it's a mindset. A mindset best expressed in a 60-slide deck to potential investors.",
    "The companies that will exist in 10 years are the ones willing to destroy everything they built in the last 5. We call this progress.",
    "Move fast and break things — just not the NDAs, the revenue forecasts, or the client relationships.",
    "Innovation is just failure with better PR. Fail loudly, pivot proudly, and always have a press release ready.",
    "Disruptive brands don't follow category conventions. They create new ones, then immediately ask McKinsey to validate them.",
    "The market doesn't need another product. It needs your product, positioned as a movement.",
    "Legacy brands are dinosaurs. And just like dinosaurs, they were enormously profitable right up until they weren't.",
    "To disrupt a market, first you must understand it deeply — then ignore everything you learned and do something completely different.",
    "The most dangerous word in business is 'established'. The second most dangerous is 'profitable'.",
    "Your competitors aren't your real threat. Your real threat is your own unwillingness to cannibalise your best-performing revenue stream.",
    "Disruption is not about technology. It's about having the audacity to charge a subscription fee for something that used to be free.",
    "We don't compete in existing categories. We create new ones, wait for competitors to enter, then call it validation.",
  ],

  data: [
    "Data doesn't lie. But it does require a very specific framing to tell the story your CMO needs to hear.",
    "We are 100% data-driven — we just also have a strong gut feeling about where the data should land.",
    "The numbers tell a story. Our job is to make sure it's the story the board approved in Q1.",
    "Big data gives us unprecedented clarity. Which is why we're more confused than ever, but with much better charts.",
    "Every decision we make is evidence-based. The evidence being that our CEO really likes this idea.",
    "We let the data speak for itself. We just do a little coaching beforehand.",
    "Data-driven marketing means never having to say you were wrong — just that the data evolved.",
    "The KPI is not the goal. The KPI is the story we tell about the goal to justify the budget.",
    "Vanity metrics are metrics your competitors track. The ones we track are called strategic indicators.",
    "If you can't measure it, it doesn't exist. Which is why we've invented 14 new metrics this quarter.",
    "Our attribution model is sophisticated enough to prove that everything we're doing is working.",
    "The best insight is the one that confirms what we already planned to do.",
    "We're a data-first organisation. Data is the first thing we look at after we've made the decision.",
    "Real-time data allows us to make faster mistakes at unprecedented scale.",
    "We have more data than ever before and less certainty than ever before. We call this maturity.",
    "The dashboard shows green. Whether that reflects reality is a philosophical question we don't have budget for.",
  ],

  purpose: [
    "Purpose-driven brands outperform on every metric. We commissioned a study that proved this. We also funded the study.",
    "Consumers want to buy from brands that stand for something. Ideally something that doesn't affect the margin.",
    "Our brand purpose is to make the world better — specifically the part of the world that can afford our premium pricing tier.",
    "Purpose is not a marketing strategy. It's a business strategy. That we express through marketing.",
    "The most powerful thing a brand can do is take a stand. On an issue that 94% of people already agree with.",
    "We're not in the business of selling products. We're in the business of selling a better future. The products fund the future-selling.",
    "Profit and purpose are not in conflict. Unless the purpose requires meaningful sacrifice, in which case we revisit the purpose.",
    "Gen Z doesn't want your product. They want your values. Fortunately, values are cheaper to produce than products.",
    "A brand without purpose is just a logo. A brand with purpose is a logo with a manifesto no one reads but everyone approves.",
    "We don't just sell coffee. We sell a morning ritual, a community, a carbon-neutral commitment, and a loyalty app.",
    "Your brand purpose should make employees proud and shareholders nervous. Then gradually make shareholders comfortable again.",
    "We did a brand purpose workshop. It took three days, cost $80,000, and we landed on 'connecting people'. Very unique.",
    "Purpose-led marketing is the future. Which is convenient because it's also an excellent justification for unmeasurable campaigns.",
    "Every brand needs a North Star. Ours points directly toward the 18-34 demographic with disposable income.",
    "We believe in a world where our product solves a problem that our marketing department invented.",
  ],

  growth: [
    "Growth hacking is just marketing with worse ethics and better funding.",
    "The secret to exponential growth is a linear increase in the number of people you call it 'exponential' to.",
    "Viral loops, referral mechanics, onboarding optimisation — if you can't pronounce it, you can't grow it.",
    "We don't acquire customers. We acquire relationships. The lifetime value of a relationship is just a customer with more steps.",
    "Product-led growth means your product does the marketing. Which is great unless your product also needs marketing.",
    "The fastest path to product-market fit is to keep redefining the market until the product fits.",
    "Growth isn't a department. It's a religion. And like all religions, it requires faith, sacrifice, and ignoring contradictory evidence.",
    "Move fast, break things, fix things slowly, quietly, after the press release.",
    "Our CAC is higher than our LTV but our NPS is excellent so we consider ourselves directionally correct.",
    "Hockey-stick growth is real. We've just been in the handle phase for four years.",
    "The best growth strategy is word of mouth. The second best is pretending you grew through word of mouth.",
    "We don't spend on marketing. We invest in growth. It's the same thing with a better slide.",
    "Retention is the new acquisition. Acquisition is the new retention. No one knows what the old acquisition was.",
    "A/B testing everything means never having to commit to a creative vision. This is called rigour.",
    "We're scaling responsibly. Which means we're scaling at the same speed but telling a better story about it.",
  ],

  ai_tech: [
    "AI won't replace marketers. It will replace marketers who don't know how to take credit for AI's work.",
    "We're an AI-first organisation. We use it for everything — except the decisions, those are still made by a committee.",
    "Machine learning has transformed our targeting. We now reach exactly the wrong people, but much faster.",
    "The future of marketing is human plus machine. The human provides the budget; the machine spends it on Instagram.",
    "Personalisation at scale means every customer gets a unique experience that's identical to everyone else's unique experience.",
    "AI allows us to create content at unprecedented volume. Quality is a separate conversation.",
    "We use AI to eliminate bias from our marketing. We then reintroduce the bias manually during the approval process.",
    "Automation doesn't remove the human touch. It automates the human touch and delivers it at 3am on a Sunday.",
    "Our AI can predict customer behaviour with 94% accuracy. The other 6% is where all our revenue comes from.",
    "The algorithm knows your customer better than you do. Which raises the question of what exactly you're for.",
    "We don't create content anymore. We prompt content. The distinction is important for budget conversations.",
    "Web3 was the future of marketing. Before that it was VR. Before that it was QR codes. The future has a short tenure.",
    "Our martech stack has 47 tools. They all integrate seamlessly, in the sense that none of them work in isolation.",
    "Digital transformation is 20% technology and 80% sending emails about digital transformation.",
    "We're leveraging AI to humanise our brand. The irony is noted and has been added to our content calendar.",
  ],

  storytelling: [
    "Every brand has a story. Ours has three — one for the board, one for the press, one for the customers.",
    "The best marketing doesn't feel like marketing. It feels like content that someone paid a lot of money to not feel like marketing.",
    "Narrative is everything. We've structured our entire go-to-market around a hero's journey where the hero is our product and the villain is our competitor's lower price point.",
    "People remember stories, not facts. Which is why our case studies are more story than case and more creative than study.",
    "Content is king. Distribution is queen. ROI is the constitutional monarch everyone respects but no one listens to.",
    "Emotional storytelling creates brand memory. Functional storytelling creates brand utility. We do both, and measure neither.",
    "The most shared content is content that makes people feel something. We aim for mild inspiration with a hint of FOMO.",
    "Your brand story should start with why. Then pivot to how. Then land on what. Then get legal to review the whole thing.",
    "We're not selling a product. We're inviting people into a narrative. The narrative has a 14-day free trial.",
    "Great storytelling is indistinguishable from great marketing. Both require a protagonist, a conflict, and a media budget.",
    "The campaign tells a story across six touchpoints. The story is: please buy this.",
    "We believe in long-form storytelling. Our terms and conditions are practically a novel.",
    "Brand journalism is the future of content marketing. It's like journalism but the editor is also the advertiser.",
    "Every touchpoint is an opportunity to reinforce the narrative. Including the invoice. Especially the invoice.",
  ],

  hustle: [
    "Wake up at 4am. Not because it helps, but because it signals to the market that you are serious.",
    "Outwork everyone. The graveyard is full of people who maintained a healthy work-life balance.",
    "Your competitors are working while you sleep. Your competitors are also burning out while you sleep. These facts coexist.",
    "Consistency is the only strategy. Post every day. Email every week. Repeat until either successful or medicated.",
    "Passion is not enough. You need passion, hustle, resilience, a warm intro to the right investors, and generational wealth.",
    "Done is better than perfect. Perfect is better for your reputation. We'll let you decide which one you're building.",
    "The market doesn't care about your mental health. Neither do your KPIs. Your LinkedIn audience, however, will engage strongly with a post about burnout.",
    "Sleep is for people who've already made it. Until you've made it, sleep is a competitive disadvantage.",
    "Your morning routine is your brand. Five AM club, journaling, cold plunge, single-origin coffee, 47-notification check.",
    "Nobody ever built an empire by having boundaries. The empire and the therapy bills come simultaneously.",
    "Fail fast, learn faster, bill the fastest. The learning is optional; the billing is not.",
    "The best time to start was yesterday. The second best time is after this 3-hour podcast about starting.",
    "Entrepreneurship is living a few years of your life like most people won't, so you can spend the rest of your life posting about it.",
    "There's no elevator to success. You have to take the stairs. Preferably while recording a motivational video about taking the stairs.",
  ],

  community: [
    "Build a community, not an audience. An audience watches. A community watches and also generates free content.",
    "Your customers are your best marketers. Activate them, empower them, and avoid compensating them wherever possible.",
    "Brand loyalty is dead. Community loyalty is alive, well, and significantly cheaper to maintain.",
    "We don't have customers. We have advocates. The distinction matters when they find out about the price increase.",
    "The most powerful marketing is word of mouth. The second most powerful is manufacturing word of mouth.",
    "Create belonging. People will pay a premium to belong to something, especially if that something validates their existing identity.",
    "Your community is your moat. Just make sure the moat has a premium subscription tier.",
    "UGC is free media. Just remember to use it, not credit it, and respond to the cease and desist quickly.",
    "Tribes are the future of marketing. Find yours, serve yours, monetise yours, pivot when yours stops converting.",
    "Community-led growth means your users acquire other users. This is only slightly different from a pyramid scheme in terms of diagrams.",
    "We don't do influencer marketing. We do community partnership. The influencer gets paid either way.",
    "Social proof is the most persuasive force in marketing. We've got 47 logos on our homepage to prove it.",
    "Turn your customers into a movement. Movements are harder to cancel than brands and require less media spend.",
  ],

  brand_performance: [
    "Brand building and performance marketing are not in conflict — as long as performance wins every budget conversation.",
    "Long-term brand investment is crucial. Which is why we cut it every Q4 and restore it every Q1 press release.",
    "The 60/40 rule is a helpful framework for explaining to your CFO why 100% of your budget is in paid search.",
    "Share of Voice drives Share of Market. We know this. We've known this for decades. We're still going to ask for a last-click attribution model.",
    "Awareness is not a vanity metric. Awareness is the foundation. We just can't put it in the dashboard so we call it vanity.",
    "Emotional advertising drives long-term growth. Rational advertising drives this quarter's growth. The quarter always wins.",
    "Brand equity is the most valuable asset on the balance sheet — which is why it's the first thing cut when the balance sheet looks bad.",
    "We believe in full-funnel marketing. Top of funnel for brand health. Bottom of funnel for actual revenue. Middle of funnel for agency fees.",
    "Distinctive brand assets are built over decades and can be destroyed in a single rebrand. We're two years into a rebrand.",
    "Mental availability is our top priority. Right after ROAS, CPA, CTR, and the CEO's favourite new channel.",
    "TV builds brand at scale. We know this. We've moved our TV budget to digital five times and moved it back four times.",
    "Mass marketing reaches people who aren't in market yet. Performance marketing reaches people who are. We only fund one of these.",
    "The best media is the media your competitor isn't in. Right now that's everywhere, because they've cut all their budgets too.",
    "We don't do brand. We do performance. Except when performance stops performing, at which point we suddenly believe in brand.",
    "Category entry points are how brands stay mentally available. We've identified ours. They're somewhere in the brand guidelines document from 2019.",
  ],

  customer_journey: [
    "The customer journey has 27 touchpoints. We own three of them and take credit for all 27.",
    "Meet your customer where they are — then follow them to five other places they didn't ask you to be.",
    "Personalisation means delivering the right message, to the right person, at the right time, approximately.",
    "The funnel is dead. The flywheel is alive. The flywheel is also just the funnel with a more optimistic diagram.",
    "Customer centricity means putting the customer at the heart of everything except the budget, the timeline, and the brief.",
    "Omnichannel is the future. One coherent experience across every channel. We're consistent in the sense that we're consistently late on all of them.",
    "We don't interrupt the customer journey. We seamlessly insert ourselves into it, 14 times, before they've finished their coffee.",
    "The zero moment of truth happens before they even know they want your product. We want to be there, watching.",
    "Friction in the customer experience is the enemy of conversion. We have eliminated all friction and replaced it with a 47-step onboarding flow.",
    "Every touchpoint should feel effortless. This effortlessness takes approximately 9 months and $2M to produce.",
    "The customer doesn't care about your organisational structure. Which is convenient, because we've restructured it four times this year.",
    "We map the customer journey annually. The customer updates it daily. We haven't spoken about this.",
    "Lifetime value starts on day one. We spend the equivalent of three years of lifetime value acquiring them on day one.",
    "Churn is just loyalty that hasn't been retained yet.",
    "The post-purchase experience is the most underinvested part of the funnel. We invest in it right after everything else.",
    "We're obsessed with the customer. We have 14 tools tracking their every move to prove it.",
    "Delight your customers at every touchpoint. Except the pricing page. That one we just make confusing.",
    "Customer success is everyone's job. Which is why no one owns it.",
  ],



  influencers: [
    "Influencer marketing is about authentic partnership. Which is why we send a 47-page contract before the first conversation.",
    "Micro-influencers have the best engagement rates. We use 200 of them simultaneously for the authentic, grassroots feel.",
    "The creator economy has democratised marketing. Anyone can build an audience. Only some of them will respond to your gifting email.",
    "We don't pay influencers. We offer them exposure, product, and the opportunity to be associated with our brand. They love it.",
    "Authenticity is why influencer marketing works. Our brief runs to 12 pages and specifies the exact lighting, angle, and approved adjectives.",
    "Find influencers who genuinely love your product. If none exist, find ones who genuinely love being paid to love your product.",
    "UGC creators are the future of content. They produce what our agency charges 40x more for, in their bedroom, overnight.",
    "The best influencer partnership feels organic. Ours felt organic right up until the ASA ruling.",
    "We measure influencer success on reach, engagement, sentiment, and whether the CEO's wife thought the post looked nice.",
    "A creator with 10,000 followers and 8% engagement beats a celebrity with 10 million followers and 0.1% engagement. We hired both to be safe.",
    "Brand affinity through creators is unmeasurable. We measure it anyway using a methodology we invented last Tuesday.",
    "We gave 50 influencers full creative freedom. Then we revised their content 11 times. Creative freedom within a framework.",
    "The right influencer makes your product feel like a discovery. The wrong one makes it feel like a sponsored post. We've done both.",
    "Nano-influencers are the most trusted voices in their niche. We activated 400 of them and the campaign still underdelivered.",
    "Content creators are media channels now. We treat them accordingly — with the same respect we show to a billboard that can reply.",
    "Ad disclosure kills authenticity. This is why we've made our disclosure text as small as legally permissible.",
  ],

  linkedin_gurus: [
    "I almost quit last year. I'm so glad I didn't. Here's what nearly losing everything taught me about personal branding. (1/12)",
    "Hot take: the best marketing strategy is being a good person. I said what I said. Drop a ❤️ if you agree.",
    "Nobody talks about this, but you can just... decide to be successful. I did it on a Tuesday. Changed everything.",
    "I turned down a €500k salary to bet on myself. Three years later, I'm making significantly less but the content writes itself.",
    "Your brand is your reputation. Your reputation is your network. Your network is your net worth. Your net worth is your brand. Repost if this helped.",
    "5 things I wish someone told me at 22: 1. Mindset is everything. 2. Network relentlessly. 3. Content is king. 4. Be authentic. 5. This post will get 400 likes.",
    "I coach 6-figure marketers to become 7-figure thought leaders. DM me 'SCALE' to find out how. (Spots limited.)",
    "Unpopular opinion: most marketers are too focused on strategy and not enough on posting about strategy.",
    "The market rewards consistency. I have posted every day for 3 years. I have not had an original thought in 18 months. The engagement is up.",
    "Someone told me my content was repetitive. I turned that criticism into a 9-post series about dealing with criticism. Thank you, haters.",
    "Real talk: building a personal brand is the single highest-ROI activity any marketer can do. Coincidentally, I sell a course on this.",
    "I failed 7 businesses before this one. Each failure taught me something invaluable. My next webinar covers all 7 for €197.",
    "Engagement hack: ask a question at the end of your post. Do you agree?",
    "I don't have clients anymore. I have transformation partners. The invoice looks the same but the relationship is fundamentally different.",
    "The algorithm rewards value. Define value as content the algorithm rewards. Post accordingly. This is strategy.",
    "Stop selling and start serving. Once you master serving, the selling becomes effortless, and the DMs asking about your pricing become the primary lead source.",
    "My mentor told me to charge what I'm worth. I now charge €3,000 per day. My mentor charges €15,000. We both teach the same thing.",
  ],

  lovebrands: [
    "A lovebrand doesn't need a reason to be loved. Reasons are for accountants. Love is for the C-suite deck.",
    "Loyalty beyond reason is the goal. Reason is the enemy of the repeat purchase.",
    "When your customer loves your brand, price becomes irrelevant. This is also what we tell ourselves when we lose on price.",
    "Lovemarks live at the intersection of high love and high respect. We're currently at high spend and high churn, but directionally similar.",
    "You don't build a lovebrand with features. You build it with feelings. Feelings that are impossible to attribute in a last-click model.",
    "Apple. Nike. Harley Davidson. These are lovebrands. So is ours. We just haven't told the customers yet.",
    "A brand becomes a lovebrand the moment consumers stop thinking and start feeling. Our job is to eliminate cognition entirely.",
    "The opposite of a lovebrand isn't a hate brand. It's a commodity. We refuse to be a commodity. We are a premium commodity.",
    "Lovemarks inspire loyalty beyond reason — which is convenient, because our product roadmap is also beyond reason.",
    "When people love your brand, they forgive your mistakes. We've stress-tested this theory extensively.",
    "The emotional connection is the product. The actual product is just how we deliver the emotional connection. Returns policy still applies.",
    "A lovebrand turns customers into evangelists. Evangelists who work for free, create content for free, and defend you online for free. We love them.",
    "High love, high respect. We have the love. The respect is in the next quarter's roadmap.",
    "You can't manufacture love. You can, however, manufacture the conditions, the content, the community, and the campaign that leads to love.",
    "Our NPS is 72. Our customers love us. Our investors love us. Our employees are working on it.",
  ],

  misc: [
    "The best marketing is marketing that doesn't look like marketing — but performs like marketing, reports like marketing, and costs like marketing.",
    "We don't have a marketing problem. We have a perception problem. These are completely different things that require identical solutions.",
    "Integrated marketing communications means all your channels say the same thing simultaneously and nobody reads any of them.",
    "The brief is a suggestion. The idea is a direction. The budget is a rumour. The deadline is very much real.",
    "Insight is the gap between what consumers say and what they do. Strategy is the gap between the insight and what we actually made.",
    "Awards don't equal effectiveness. Effectiveness doesn't equal awards. We pursue both and achieve neither.",
    "The rebrand will fix it.",
  ],
  
  vibecoding: [
    "Vibe coding is the future of marketing technology. Why hire a developer when you can prompt one?",
    "We rebuilt our entire martech stack using AI. It took 3 hours and works 60% of the time, which is better than the original.",
    "Our new campaign microsite was vibe-coded in an afternoon. The brief took three weeks.",
    "I don't write briefs anymore. I vibe-prompt. The output is indistinguishable from what our agency produced, and costs 400x less.",
    "The best marketing tech is the tech you built yourself at 11pm on a Tuesday without knowing how to code.",
    "Vibe coding democratises marketing technology. Everyone can now build tools that half-work equally.",
  ],
};

// Flatten all quotes into one array
export const ALL_QUOTES = Object.values(QUOTES_BY_CATEGORY).flat();

// Total count helper
export const QUOTE_COUNT = ALL_QUOTES.length;
export const MARKETER_COUNT = MARKETERS.length;
// PATCH: lovebrands quotes added separately
